### ISSUE TITLE
Port Code With Us Page to Jekyll

### ISSUE THREAD

**Issue by sheaphillips** [BCDevExchange/BCDevExchange-Site#1]
As a Developers' Exchange team member, I want to port the existing Code With Us page to the new Jekyll architecture from the current structure.  This includes both the general layout and static elements, as well as the dynamic "issue list" widgets. The initial proposal for the issue list is to implement a minimal nodejs (sailsjs) app that serves up a "widget" to be embedded as an iFrame in the Jekyll site.

**Comment by ccoldwell** [comment]
this is everything else
