### ISSUE TITLE
Developers: "Open Opportunities" nav to profiles and issues broken

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#11]
![screen shot 2016-08-04 at 4 00 58 pm](https://cloud.githubusercontent.com/assets/9368818/17421186/c171f7c2-5a5c-11e6-9528-0ca5b43778c1.png)

**Comment by kelpisland** [comment]
Still getting a 404 when I click the "partner" link and nothing happens when I click the "issue"
![screen shot 2016-08-16 at 3 08 49 pm](https://cloud.githubusercontent.com/assets/9368818/17717564/9f585a58-63c3-11e6-9ff1-2e6fc285e1dd.png)

![screen shot 2016-08-16 at 3 07 03 pm](https://cloud.githubusercontent.com/assets/9368818/17717551/81b52cba-63c3-11e6-96e7-4fcb4353cde9.png)

**Comment by ccoldwell** [comment]
this should be good now, I removed the links to the programs though as those would have to be hard-coded for each individual program without having some other meta-data attached to the mini-app.  if this is a firm requirement then I can do the typing but it will be a hand coding step if we add or remove programs

**Comment by kelpisland** [comment]
All good
