### ISSUE TITLE
Programs: short list missing

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#12]
The list in the new site has the wrong content.
1. no logos
2. short description
3. tags

![screen shot 2016-08-04 at 4 09 46 pm](https://cloud.githubusercontent.com/assets/9368818/17421390/4aa1a9ce-5a5e-11e6-8800-e1e2711dd1e7.png)

**Comment by ccoldwell** [comment]
alright, merged data from directory and mongo to get this, tags used to use the first 6 characters of the mongo id for a colour, so pick one :-)

**Comment by kelpisland** [comment]
I like the grey scale better - let's go with this as MVP prior to move to open opportunities
