### ISSUE TITLE
Programs: search box missing

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#13]
![screen shot 2016-08-04 at 4 14 32 pm](https://cloud.githubusercontent.com/assets/9368818/17421441/a2f7d5b2-5a5e-11e6-8ac8-09d55f972657.png)

**Comment by ccoldwell** [comment]
we do not have a facility to search since there is no javascript running here.  We could try to make one since we likely will for blogs anyhow.  We should talk about it though

**Comment by kelpisland** [comment]
OK - if that's the case lets not pending move to Open Opportunities
