### ISSUE TITLE
Site wide: quick scroll button missing

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#16]
![screen shot 2016-08-04 at 4 24 27 pm](https://cloud.githubusercontent.com/assets/9368818/17421620/0e5385bc-5a60-11e6-8bb3-5f851cb876db.png)

Bottom right of all long pages should have a quick scroll button that auto shows/hides when moving from top to bottom.

**Comment by ccoldwell** [comment]
I'm not seeing this in the old site anywhere

**Comment by kelpisland** [comment]
You're right - it's gone, weird! OK in that case let's not lose sleep over that one.
