### ISSUE TITLE
Privacy: Footer Nav is on 3 lines, should be 2

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#17]
![screen shot 2016-08-04 at 4 33 01 pm](https://cloud.githubusercontent.com/assets/9368818/17421768/43afb55e-5a61-11e6-8000-b5c2a0d07eed.png)

**Comment by ccoldwell** [comment]
complete - please verify

**Comment by kelpisland** [comment]
![screen shot 2016-08-08 at 3 09 36 pm](https://cloud.githubusercontent.com/assets/9368818/17498124/31068a74-5d7a-11e6-8ecc-b1efcd40a22e.png)
There seems to be some sort of padding forcing the footer to the left

**Comment by ccoldwell** [comment]
when I go back and forth from bcdevexchange.org and my local site the footers look identical. what browser are you using?

**Comment by kelpisland** [comment]
I'm using Safari and Chrome. What I see is a bunch of padding/ white space on the left that causes the footer to pushed over to the right.
![screen shot 2016-08-10 at 2 19 08 pm](https://cloud.githubusercontent.com/assets/9368818/17571574/a8b56c16-5f05-11e6-815f-fded09b5ad1b.png)
