### ISSUE TITLE
Blog Tags

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#19]
![screen shot 2016-08-08 at 3 34 33 pm](https://cloud.githubusercontent.com/assets/9368818/17498679/ab8d9726-5d7d-11e6-8429-93128d8595a6.png)
We need tags for the new Jekyll blog page - I figured this is more a comms thing, let me know if you'd like me to just "wing" it.

**Comment by ccoldwell** [comment]
I think this is a winging it thing.  Not sure if there is a facility in prose for adding tags (they are in the yaml header).  Also would be great to have people edit the description yaml field.

**Comment by kelpisland** [comment]
No tags was the vote
