### ISSUE TITLE
Profile pages should have "stats" removed

### ISSUE THREAD

**Issue by sheaphillips** [BCDevExchange/BCDevExchange-Site#20]
![screenshot 2016-08-11 17 00 49](https://cloud.githubusercontent.com/assets/698658/17608953/350ed744-5fe5-11e6-97e1-6efd51259a01.png)

It's broken and not crucial to be included.

**Comment by kelpisland** [comment]
Agree - ditch 'em

**Comment by kelpisland** [comment]
Validated
