### ISSUE TITLE
Embedded gitter should be removed from bottom of profile pages

### ISSUE THREAD

**Issue by sheaphillips** [BCDevExchange/BCDevExchange-Site#21]
![screenshot 2016-08-11 17 02 34](https://cloud.githubusercontent.com/assets/698658/17608984/745a79c6-5fe5-11e6-9abc-a94dc3d48455.png)

**Comment by kelpisland** [comment]
Yep - never used, ditch it.

**Comment by kelpisland** [comment]
Validated
