### ISSUE TITLE
Profile pages icon links broken

### ISSUE THREAD

**Issue by sheaphillips** [BCDevExchange/BCDevExchange-Site#22]
![screenshot 2016-08-11 17 05 07](https://cloud.githubusercontent.com/assets/698658/17609013/c6a5c154-5fe5-11e6-8cf1-e17448c4ce16.png)

Links should be page-relative anchor links, but they appear to be absolute and end up taking you to the home page instead of scrolling to the pertinent section on the current profile page.

**Comment by kelpisland** [comment]
this one is partially fixed and now replaced by #25
