### ISSUE TITLE
Blank CWU grid

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/BCDevExchange-Site#23]
The grid appears to be empty until I add a "help wanted" tag to an issue in the old DevEx-app repo

![screen shot 2016-08-12 at 12 03 58 pm](https://cloud.githubusercontent.com/assets/11237533/17633979/0d54cede-6085-11e6-8191-bc8d8bd76a10.png)

**Comment by sheaphillips** [comment]
Oddly, the list is blank for me, even after Paul managed to make it visible
by adding the tag...

There is a CORS error/warning in the console, but I _think_ that's to do
with the resize and not the tables/content themselves...

<img width="871" alt="screenshot 2016-08-12 12 05 15" src="https://cloud.githubusercontent.com/assets/698658/17635413/108f2a52-608c-11e6-86ef-0af41f728425.png">

**Comment by kelpisland** [comment]
Validated
