### ISSUE TITLE
Developers: "Closed Opportunities" nav to profiles and issues broken

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#26]
Same issue as #8 but on the closed table.

Text reads 'Done' should be "Closed Opportunities" in larger font

**Comment by ccoldwell** [comment]
made the same (h2) but not sure it will be satisfactory.  the entire markup in the dev version is completely different than what is in prod for some reason

**Comment by kelpisland** [comment]
All good
