### ISSUE TITLE
Home: "view partners" link changes to blue after followed - should stay white

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#4]
![screen shot 2016-08-04 at 3 21 16 pm](https://cloud.githubusercontent.com/assets/9368818/17420396/3a442c2a-5a57-11e6-93d6-ce656865261e.png)

**Comment by ccoldwell** [comment]
complete - please verify

**Comment by kelpisland** [comment]
Same odd behaviour as #5
