### ISSUE TITLE
Home: "explore APIs" link changes to blue after followed - should stay white

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#5]
![screen shot 2016-08-04 at 3 34 06 pm](https://cloud.githubusercontent.com/assets/9368818/17420657/f7fa9906-5a58-11e6-8823-6a13866b0a15.png)

**Comment by ccoldwell** [comment]
complete - please verify

**Comment by kelpisland** [comment]
OK - it's better-ish. For some reason the link stays blue after re-load until there is another event like mouse move, or mouse over. After "any" manual browser event the link turns white, is there a way to make that less wonky?
