### ISSUE TITLE
Menu: Top nav titles should be bold

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#6]
![screen shot 2016-08-04 at 3 35 54 pm](https://cloud.githubusercontent.com/assets/9368818/17420704/47e9d558-5a59-11e6-9b21-76f79a7571cd.png)
![screen shot 2016-08-04 at 3 36 06 pm](https://cloud.githubusercontent.com/assets/9368818/17420705/49b576b2-5a59-11e6-825a-31f380ac0e70.png)

**Comment by ccoldwell** [comment]
complete - please verify

**Comment by kelpisland** [comment]
All good
