### ISSUE TITLE
Site Wide: Font miss match (size and style)

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#7]
![screen shot 2016-08-04 at 3 41 10 pm](https://cloud.githubusercontent.com/assets/9368818/17420802/f9169ef6-5a59-11e6-8b53-36286da3fc7a.png)

Helvetia (old site, right)
OpenSans (new site, left)

Close but Open Sans is wider and seems to be missing header weight.

**Comment by ccoldwell** [comment]
complete - please verify

**Comment by kelpisland** [comment]
Great - much closer, new site font is a bit narrower but looks good
