### ISSUE TITLE
Developers: "Open Opportunities" title missing

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#8]
![screen shot 2016-08-04 at 3 51 40 pm](https://cloud.githubusercontent.com/assets/9368818/17421019/640bbec0-5a5b-11e6-9660-7df9388cb7fa.png)

**Comment by ccoldwell** [comment]
this is different now as the titles on individual lists are provided form the mini-app (open, closed, blocked, in progress).  all other content is in markdown or html in the site itself, so it can say whatever

**Comment by kelpisland** [comment]
OK - I'l verify after we have a build including the mini-aps

**Comment by kelpisland** [comment]
Title still missing, the current text at the top of the table 'Open (1)' too small.

**Comment by ccoldwell** [comment]
same same but different

**Comment by kelpisland** [comment]
All good
