### ISSUE TITLE
Developers: Closed Opportunities" table missing

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-Site#9]
![screen shot 2016-08-04 at 3 52 40 pm](https://cloud.githubusercontent.com/assets/9368818/17421053/8f6ebc8e-5a5b-11e6-94ab-2005f796f508.png)

**Comment by ccoldwell** [comment]
this will show once the mini-app is working properly, I think the latest version is not deployed

**Comment by kelpisland** [comment]
Still not working, I only get Open issues. Closed list missing.

**Comment by kelpisland** [comment]
Validated
